/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b4c7ec",
        "surface-container": "#f0eded",
        "background-primary": "#FDFBF7",
        "clinical-blue-muted": "#2C4365",
        "on-primary-fixed-variant": "#344766",
        "on-tertiary-fixed": "#281800",
        "on-tertiary": "#ffffff",
        "secondary-container": "#eadecd",
        "on-tertiary-container": "#b18f5d",
        "on-surface": "#1b1c1c",
        "surface-variant": "#e4e2e1",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#e6c18a",
        "on-primary-container": "#8396b8",
        "surface-bright": "#fbf9f8",
        "tertiary-container": "#3f2901",
        "error-container": "#ffdad6",
        background: "#fbf9f8",
        "on-primary-fixed": "#051c38",
        "secondary-fixed-dim": "#d0c5b5",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        "surface-container-high": "#eae8e7",
        "on-surface-variant": "#44474d",
        "on-background": "#1b1c1c",
        "surface-tint": "#4c5f7f",
        surface: "#fbf9f8",
        "background-subtle": "#E6DED2",
        "on-tertiary-fixed-variant": "#5c4217",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f6f3f2",
        secondary: "#665d50",
        "inverse-on-surface": "#f3f0f0",
        primary: "#021935",
        "inverse-surface": "#303030",
        "primary-container": "#1a2e4b",
        "surface-dim": "#dcd9d9",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ffddaf",
        "surface-container-highest": "#e4e2e1",
        "surface-border": "#D1C9BC",
        "primary-fixed": "#d5e3ff",
        "secondary-fixed": "#ede1d0",
        "on-secondary-container": "#6a6154",
        "inverse-primary": "#b4c7ec",
        "outline-variant": "#c4c6ce",
        tertiary: "#241600",
        "on-secondary-fixed-variant": "#4d4639",
        outline: "#74777e",
        "on-secondary-fixed": "#201b10",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1200px",
        "stack-md": "24px",
        "margin-mobile": "20px",
        unit: "4px",
        "stack-sm": "12px",
        "stack-lg": "48px",
        "margin-desktop": "64px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-md": ["Noto Serif"],
        "body-md": ["Manrope"],
        "label-caps": ["Manrope"],
        button: ["Manrope"],
        "headline-lg-mobile": ["Noto Serif"],
        "display-lg": ["Noto Serif"],
        "headline-lg": ["Noto Serif"],
        "body-lg": ["Manrope"],
      },
      fontSize: {
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        button: ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
